name: zoeguard_web
description: A Flutter web project for ZOEGUARD
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (compatible)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_analytics: ^12.0.3
  firebase_storage: ^13.0.3
  
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.0.1
  # # Image picker
  file_picker: ^5.4.0
  crop_your_image: ^1.0.4


  # Maps & location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_heatmap: ^0.0.3
  location: ^8.0.1
  http: ^1.2.1
  geolocator: ^14.0.2
  # Utilities
  path_provider: ^2.1.5
  uuid: ^4.5.1
  characters: ^1.4.0
  meta: ^1.16.0
  material_color_utilities: ^0.11.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/animations/particles.lottie
  - assets/animations/sheild.lottie

